<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;


class Credit extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'client_id', 'value', 'fee', 'type', 'revenue', 'start_at', 'active',
    ];

    /**
	* The attributes that should be hidden for arrays.
	*
	* @var array
	*/
	protected $hidden = [
		'created_at', 'updated_at'
	];

	/**
     * Get the client that owns the credit.
     */
    public function client()
    {
        return $this->belongsTo('App\Client');
    }

	/**
     * Get all payments for the credit.
     */
    public function payments()
    {
        return $this->hasMany('App\Payment');
    }

    /**
     * Get the profit generated by the credit.
     */
    public function profit()
    {
        return ($this->value * $this->revenue) / 100;
    }

    /**
     * Get total money to pay for the credit.
     */
    public function total_to_pay()
    {
        return $this->value + $this->profit();
    }

    /**
     * Get total money paid for the credit.
     */
    public function total_paid()
    {
        return $this->payments->sum('value');
    }

    /**
     * Get value of the fee.
     */
    public function fee_val()
    {
        return $this->total_to_pay() / $this->fee;
    }

    /**
     * Get credit balance.
     */
    public function balance()
    {
        return $this->total_to_pay() - $this->total_paid();
    }
}
